services:
    app:
        build: .
        ports:
            - '3005:3005'
        environment:
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - IS_DOCKER=${IS_DOCKER}
        volumes:
            - chalk-data:/app/data

volumes:
    chalk-data:
